
Info:
  MouseID: V1A1
  Note: ''
  Session: ''
  TaskType: 3tones-change-classical


Preferences:
  HeartBeat: 250 # ms
  AudioFileDirectory: '/mnt/d/Development/Design/TreadmillTracker/ClientSide/Tasks/HeadFixedTask/Sounds'

GPIO:
  Dispense: 27
  Lick: 16

Maze:
  EncoderGain: 4096.0 # encoder value per revolution
  Length: 150.0 # cm
  WheelDiameter: 20.2 # cm

AuditoryStimuli:
  Defaults:
    Filename: '' # if no filename is specified, we'll raise an error later
    Type: 'Localized'
    CenterPosition: 0.0
    BaselineGain: 0.0 # Max gain for linear stimuli
    Modulation:
      Type: Linear
      #Rate: -20.0 # dB/cm
      Width: 25 # cm in which sound is on (full width)
      CutoffGain: -60.0 #dB at cutoff

  StimuliList:
    BackgroundSound:
      Type: 'Background'
      BaselineGain: -5.0
      Filename: 'pink_noise.wav'
      Color: 'pink'
    Zone_1:
      CenterPosition: 12.5 
      Filename: 'tone_3kHz.wav'
      Color: 'lime'
    Zone_2:
      CenterPosition: 62.5 
      Filename: 'tone_7kHz.wav'
      Color: 'red'
    Zone_3:
      CenterPosition: 102.5 
      Filename: 'tone_10kHz.wav'
      Modulation:
        Width: 25
      Color: 'orange'

RewardZones:
  RewardZoneList:
    Reward1:
      Type: 'Operant'
      LickPin: 1
      DispensePin: 7
      PumpRunTime: 100 # How long to run the reward pump for
      LickTimeout: 3000.0 # Time between reward availability
      MaxSequentialRewards: 5
      RewardZoneStart: 110
      RewardZoneEnd: 130
      ResetZoneStart: 20
      ResetZoneEnd: 70
      Color: 'green'


